### ISSUE TITLE
Build as a transformer

### ISSUE THREAD

**Issue by chasemccoy** [nhducit/gatsby-plugin-mdx#14]
There is some more in depth discussion going on over here: https://github.com/gatsbyjs/gatsby/issues/5200 that concerns how this plugin and Gatsby work together. I thought you may want to take a look!

**Comment by ChristopherBiscardi** [comment]
Thanks for letting us know :)

If you're still looking for a way to access the raw code, perhaps make a comment [on this issue](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/13) with a potential use case. We'll soon have a way to [dynamically create mdx nodes](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/33) as well, which I believe should solve all use cases.

(Note that the links above are to the gatsby 2.0 compatible plugin, which is being developed in a separate repo and has richer feature support than the 1.0 compatible one here)
