### ISSUE TITLE
Ability to customize markdown html tags

### ISSUE THREAD

**Issue by slorber** [nhducit/gatsby-plugin-mdx#17]
Hi,

Just want to create an issue to explain how to add custom style support for markdown html elements.

The MDX component exported does permit to customize the rendering of tags (H1, code etc...) but as Gatsby does not currently allow to wrap our component, The only way I've found to make this working was by using a webpack alias to create a custom MDXTag component (the component exported by MDX loader)

```js
exports.modifyWebpackConfig = ({ config, stage }) => {
  config.merge({
    resolve : {
      alias: {
        '@mdx-js/tag': path.resolve(__dirname, 'src/components/MdxTagCustom.js'),
      }
    }
  });
};
```

```js
import React from 'react'
import PropTypes from 'prop-types'

const H1 = props => <h1 style={{ color: 'tomato' }} {...props} />
const InlineCode = props => <code id="codes" style={{ color: 'purple' }} {...props} />
const Code = props => <code id="codes" style={{ fontWeight: 600 }} {...props} />
const Pre = props => <pre id="codes" style={{ color: 'blue' }} {...props} />

const components = { h1: H1, pre: Pre, code: Code, inlineCode: InlineCode };

const defaults = {
  inlineCode: 'code',
  wrapper: 'div'
}

export const MDXTag = props => {
  const {
    name,
    parentName,
    props: childProps = {},
    children,
  } = props
  const Component =
    components[`${parentName}.${name}`] ||
    components[name] ||
    defaults[name] ||
    name
  return <Component {...childProps}>{children}</Component>
}
```

The component above is almost the same as the original one except we provide our custom components instead of a default components={} prop

Note that if MDX allowed to provide the components prop with React context that would be more convenient for Gatsby as we could put a components provider in the layout. See https://github.com/mdx-js/mdx/issues/153

**Comment by slorber** [comment]
hey, just want to add that they added the MDXProvider so it should be easy to setup custom tags with it on Gatsby by using a provider at the layout /template level, so I'm closing this

https://github.com/mdx-js/mdx#mdxprovider

**Comment by nhducit** [comment]
thanks @slorber for the update.
