### ISSUE TITLE
[Question] Using with frontmatter?

### ISSUE THREAD

**Issue by mpolinowski** [nhducit/gatsby-plugin-mdx#19]
I am trying to get the mdx plugin to work with the Gatsby default blog starter. Is it possible to use the plugin with a Markdown file that contains Frontmatter / is there starter or sample code for it somewhere?

**Comment by ChristopherBiscardi** [comment]
This is possible with the gatsby 2.0 compatible version of mdx integration which is available [here](https://github.com/ChristopherBiscardi/gatsby-mdx). It supports classic frontmatter as well as exports directly from mdx files.
