### ISSUE TITLE
Image optimisation

### ISSUE THREAD

**Issue by falconmick** [nhducit/gatsby-plugin-mdx#7]
I have just finished setting up a Gatsby website using gatsby-transformer-remark and I was left wishing I could also use JSX inside of it. Until I found this gem! However I am unable to find any documentation that would leave me to believe that this project has any plugins like gatsby-remark-images or gatsby-remark-copy-linked-files so I am left unable to tell if I can use this plugin to achive the same thing as remark, but with the added benifit of jsx.

Any input?

**Comment by nhducit** [comment]
hi @falconmick,

This plugin only helps us use `mdx` in Gatsby. I'm not sure if `mdx` support all your requirements. You should check in mdx document

**Comment by nhducit** [comment]
```
mdx-js/mdx uses Remark to parse Markdown into an MDAST which is transpiled to MDXAST. This allows for the rich unified plugin ecosystem to be utilized while also ensuring a more robust parsing implementation by sharing the Remark parser library.
```
You can use mdx along with `remark-images` e.g. 

```
          options: {
            mdPlugins: [images]
          }
```

https://github.com/mdx-js/mdx/blob/e1423eaec7f09b25021e58509a810cc3258f741f/examples/next/next.config.js#L13

```
const images = require('remark-images')

module.exports = {
  pageExtensions: ['js', 'jsx', 'md', 'mdx'],
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      test: /\.md$/,
      use: [
        defaultLoaders.babel,
        {
          loader: '@mdx-js/loader',
          options: {
            mdPlugins: [images]
          }
        }
      ]
    })

    return config
  }
}
```

**Comment by avigoldman** [comment]
Is this possible to do with this plugin? Can we add an option for this?

.i.e.

```
const images = require('remark-images')

....

{
  resolve: 'gastby-plugin-mdx',
  options: {
    mdPlugins: [images],
  },
},

**Comment by nhducit** [comment]
@avigoldman we can add option for this plugin. let me know if you want to create PR

**Comment by avigoldman** [comment]
Looking into it, it seems like Gatsby uses webpack 1 and I believe we need a later version of webpack for this to work. [Waiting on an answer](https://github.com/gatsbyjs/gatsby/issues/312#issuecomment-388148944) from the Gatsby team.

I think this will work once Gatsby 2.0 is out.

**Comment by nhducit** [comment]
oh, then this example use mdx with next.js (which use newer webpack version). I thought we can follow same configuration for gatsby

```
const images = require('remark-images')

module.exports = {
  pageExtensions: ['js', 'jsx', 'md', 'mdx'],
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      test: /\.md$/,
      use: [
        defaultLoaders.babel,
        {
          loader: '@mdx-js/loader',
          options: {
            mdPlugins: [images]
          }
        }
      ]
    })

    return config
  }
}
```

**Comment by ChristopherBiscardi** [comment]
Moving the image optimization conversation to https://github.com/ChristopherBiscardi/gatsby-mdx/issues/10, which is the gatsby 2.0 compatible mdx integration. Please continue discussion there :)
